#!/bin/bash
################################################################################
# zmbackup - Bash script to hot backup and hot restore Zimbra Collaboration
#            Suite Opensource
#
# Copyright (C) 2017 Lucas Costa Beyeler <lucas.costab@outlook.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 2 of the GNU General Public
# License as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#
################################################################################
# zmbkpose:
#
# 26/10/2010 - Version 1.0.5 - By Alan Nikitiuk Milani
#                              <alan.milani@4linux.com.br>
#                              <niki.milani@gmail.com>
#
#                              Bruno Gurgel
#                              <bruno@4linux.com.br>
#                              <bruno.gurgel@gmail.com>
#
# 24/05/2012 - Version 2.0 Beta - By William Felipe Welter
#                                 <william.welter@4linux.com.br>
#                                 <wfelipew@gmail.com>
################################################################################
# zmbackup:
#
# 28/09/2018 - Version 1.2.3  - By The Zimbra Community & Lucas Costa Beyeler
#                               <lucas.costab@outlook.com>
#                               <zmbackup@protonmail.com>
################################################################################
# zmbackup:
#
# 17/04/2020 - Version 2.0.0  - By Vinicius Becker
#                               <vinicius@becker.eti.br>
################################################################################
# parallel:
#
#   O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
#   The USENIX Magazine, February 2011:42-47.
#
################################################################################
# LOADING ZMBACKUP LIBRARIES
################################################################################
source /opt/zmbackup/lib/Help.sh
source /opt/zmbackup/lib/Misc.sh
source /opt/zmbackup/lib/Notify.sh
source /opt/zmbackup/lib/Parallel.sh
source /opt/zmbackup/lib/List.sh
source /opt/zmbackup/lib/Backup.sh
source /opt/zmbackup/lib/Restore.sh
source /opt/zmbackup/lib/Delete.sh
source /opt/zmbackup/lib/Migration.sh
source /opt/zmbackup/lib/Session.sh

################################################################################
# ZMBACKUP MAIN CODE
################################################################################
VERSION="2.0.0"

load_config
validate_config
export_function
export_vars
constant
case "$1" in
  "-f"|"--full" )
    checkpid
    case "$2" in
      "-dl"|"--distributionlist" )
        sessionvars $2
        create_temp
        backup_main $DLOBJECT $DLFILTER $3 $4
        rm -rf $PID
      ;;
      "-al"|"--alias" )
        sessionvars $2
        create_temp
        backup_main $ALOBJECT $ALFILTER $3 $4
        rm -rf $PID
      ;;
      "-l"|"--ldap" )
        sessionvars $2
        create_temp
        backup_main $ACOBJECT $ACFILTER $3 $4
        rm -rf $PID
      ;;
      "-m"|"--mailbox" )
        sessionvars $2
        create_temp
        backup_main $ACOBJECT $ACFILTER $3 $4
        rm -rf $PID
      ;;
      "-sig"|"--signature" )
        sessionvars $2
        create_temp
        backup_main $SIOBJECT $SIFILTER $3 $4
        rm -rf $PID
      ;;
      * )
        sessionvars $1
        create_temp
        backup_main $ACOBJECT $ACFILTER $2 $3
        rm -rf $PID
      ;;
    esac
  ;;
  "-l"|"--list" )
    list_sessions
  ;;
  "-r"|"--restore" )
    create_temp
    checkpid
    case "$2" in
      "-dl"|"--distributionlist"|"-l"|"--ldap"|"-al"|"--alias"|"-sig"|"--signature")
        restore_main_ldap $3 $4 $5
        rm -rf $PID
      ;;
      "-m"|"--mailbox" )
        restore_main_mailbox $3 $4 $5
        rm -rf $PID
      ;;
      "-ro"|"--restoreOnAccount" )
        if [ -z "$4" ] || [ -z "$5" ]; then
          show_help
          printf "\n\nError! Please inform the account that should be restored, and when the restore should be placed.\n\n"
          exit 2
        else
          constant
          restore_main_mailbox $3 $4 $5
          rm -rf $PID
        fi
      ;;
      * )
        if [[ "$2" == "full"* ]]; then
          constant
          restore_main_ldap $2 $3 $4
          restore_main_mailbox $2 $3 $4
          rm -rf $PID
        else
          show_help
          printf "\n\nError! Invalid parameters for restore\n"
        fi
      ;;
    esac
  ;;
  "-d"|"--delete" )
    if [ -z "$2" ]; then
      show_help
      printf "\n\nError! Please inform the session that should be deleted\n\n"
    else
      checkpid
      delete_one $2
      rm -rf $PID
    fi
  ;;
  "--housekeep")
    checkpid
    delete_old
    clean_empty
    rm -rf $PID
  ;;
  "-t"|"--truncate")
    if [ ! -z "$2" ] && [ "--force-clean" == "$2" ]; then
      checkpid
      leeroy_jenkins
      clean_empty
      rm -rf $PID
    else
      echo "This action is irreversible - Use the option --force-clean to override this message"
    fi
  ;;
  "-h"|"--help" )
    show_help
  ;;
  "-v"|"--version" )
    echo "zmbackup version: $VERSION"
  ;;
  "-m"|"--migrate" )
    checkpid
    migration
    rm -rf $PID
  ;;
  * )
    show_help
    printf "\n\nError! Incorrect options\n\n"
  ;;
esac
exit 0
